### ISSUE TITLE
[runtime/memory plot] add % scale on right side axis

### ISSUE THREAD

**Issue by martin-raden** [BackofenLab/IntaRNA-benchmark#11]
would be good to have % scale as an additional axis on the respective right sides of the plots as suggested by @fulanko

**Comment by martin-raden** [comment]
mhh.. maybe we need an additional plot for that, since currently "delta" values are reported and no absolute values accessible..

**Comment by RickGelhausen** [comment]
Plotting has been changed to a combination of line and violin plots.
