### ISSUE TITLE
number of threads as arg in qsub call

### ISSUE THREAD

**Issue by martin-raden** [BackofenLab/IntaRNA-benchmark#13]
https://github.com/BackofenLab/IntaRNA-benchmark/blob/97596f5b4f30a140c5ed019d025a51336f9c2722/intarna-benchmark-sge.sh#L4

please test: if giving the number of threads also as qsub call argument, which one has priority?

if not working at all (specifying at both places) remove from sge script to be more flexible..

**Comment by RickGelhausen** [comment]
The qsub call argument has priority:
`qsub -pe smp 12 intarna-benchmark-sge.sh ... `
