### ISSUE TITLE
insufficient checks for precomputed ED

### ISSUE THREAD

**Issue by martin-raden** [BackofenLab/IntaRNA-benchmark#14]
https://github.com/BackofenLab/IntaRNA-benchmark/blob/97596f5b4f30a140c5ed019d025a51336f9c2722/bin/calls.py#L102

will fail if q/tAccW/L (or q/tIntLenMax) are added in the call, since these alter the span for unpaired probs

best test for these parameters and report error if present.

alternatively: add another argument for the maximal interaction length needed from the precomputed ED values

**Comment by RickGelhausen** [comment]
- added argument for the maximal interaction length 
- added check for q/tAccW/L (or q/tIntLenMax) detection and error message
