### ISSUE TITLE
violine plots for various max-rank thresholds

### ISSUE THREAD

**Issue by martin-raden** [BackofenLab/IntaRNA-benchmark#4]
to increase interpretation power, it would be good to get instead of a single violine plot per line a set for different (user defined?) thresholds, ie. next to each other for up to rank 5, 10, 50, 100, 200

this will reveal whether a call is better already for the top ranked or only for longer result lists

**Comment by martin-raden** [comment]
@RickGelhausen could you please have a look (no hurry... somewhen in the future)

**Comment by RickGelhausen** [comment]
Do you mean one plot per set of thresholds ?
i.e. one plot for each callID including a violin for 5, 10, 50, 100, 200 target predictions.
When plotting all callIDs into one plot, this method becomes very confusing, due to overlapping.

**Comment by martin-raden** [comment]
@RickGelhausen that was covered by the last pull request #5 right?

**Comment by RickGelhausen** [comment]
@martin-mann yes
